export const skillOptions = [
  { label: "HTML", value: "html" },
  { label: "CSS", value: "css" },
  { label: "Tailwind CSS", value: "tailwind" },
  { label: "JavaScript", value: "javascript" },
  { label: "TypeScript", value: "typescript" },
  { label: "React", value: "react" },
  { label: "Next.js", value: "nextjs" },
  { label: "Redux", value: "redux" },
  { label: "Vue", value: "vue" },
  { label: "Angular", value: "angular" },
  { label: "Node.js", value: "node" },
  { label: "Express", value: "express" },
  { label: "NestJS", value: "nestjs" },
  { label: "GraphQL", value: "graphql" },
  { label: "REST APIs", value: "rest" },
];
